language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  except:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  - export TZ=Europe/Berlin

script:
  - ./gradlew init
  - ./gradlew test
